version: '3'

services:
  server:
    image: nginx:alpine
    container_name: nginx 
    volumes:
      - ./wp:/usr/share/nginx/html/wordpress
      - ./wordpress.conf:/etc/nginx/conf.d/wordpress.conf
    ports:
      - 3000:3000
    depends_on:
      - mysql
    links:
      - php-fpm

  mysql:
    image: mysql:8.1.0
    volumes:
        - sqldata:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306

  php-fpm:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=mysql
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
    volumes:
      - ./wp:/usr/share/nginx/html/wordpress
    depends_on:
      - mysql

volumes:
  sqldata:

